### ISSUE TITLE
_curses.error: [mv]wdelch() returned ERR

### ISSUE THREAD

**Issue by ivan** [facebook/PathPicker#179]
On Ubuntu 14.04 or 15.10 (2015-08-15),

```bash
git clone https://github.com/facebook/PathPicker
cd PathPicker
find . | ./fpp
```

then press `A` and observe:

```
Traceback (most recent call last):|space|b] navigation, [enter] open, [x] quick select mode, [c] command mode
  File "/home/at/PathPicker/src/choose.py", line 97, in <module>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/at/PathPicker/src/choose.py", line 97, in <lambda>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/home/at/PathPicker/src/choose.py", line 43, in doProgram
    screen.control()
  File "/home/at/PathPicker/src/screenControl.py", line 293, in control
    self.processDirty()
  File "/home/at/PathPicker/src/screenControl.py", line 526, in processDirty
    self.clearLine(y)
  File "/home/at/PathPicker/src/screenControl.py", line 543, in clearLine
    self.stdscr.delch(y, x)
_curses.error: [mv]wdelch() returned ERR
```

**Comment by pcottle** [comment]
Thanks for the bug report and repro case @ivan ! This is totally a bug -- there is only one way you can select files that are offscreen, and thats with the "A" command. youll see in the attached commit that this was a silly fix :P

adding some test coverage...

**Comment by pcottle** [comment]
Done! Should be fixed, thanks again :+1:
