### ISSUE TITLE
shell script assumes Python2 command name is 'python'

### ISSUE THREAD

**Issue by fczuardi** [facebook/PathPicker#292]
If installed on a system where `python` means Python 3, the `--command` option will fail with the following traceback:

```
Traceback (most recent call last):
  File "/opt/PathPicker/src/choose.py", line 104, in <module>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/opt/PathPicker/src/choose.py", line 104, in <lambda>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/opt/PathPicker/src/choose.py", line 46, in doProgram
    screen.control()
  File "/opt/PathPicker/src/screenControl.py", line 366, in control
    self.processInput(inKey)
  File "/opt/PathPicker/src/screenControl.py", line 462, in processInput
    self.onEnter()
  File "/opt/PathPicker/src/screenControl.py", line 607, in onEnter
    output.execComposedCommand(presetCommand, lineObjs)
  File "/opt/PathPicker/src/output.py", line 42, in execComposedCommand
    command = composeCommand(command, lineObjs)
  File "/opt/PathPicker/src/output.py", line 145, in composeCommand
    return composeFileCommand(command, lineObjs)
  File "/opt/PathPicker/src/output.py", line 149, in composeFileCommand
    command = command.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

This happens because it is trying to run it with the system python, set on this line: https://github.com/facebook/PathPicker/blob/master/fpp#L23

It would be nice to have a better way to look for the correct installed python2, maybe checking first if a `python2` is there and fallback to `python` if not.

**Comment by fczuardi** [comment]
Yes, it is `/usr/bin/python2` but it didn't come with the system (Antergos Linux), I have installed the [python2 package](https://www.archlinux.org/packages/?name=python2) for other reasons.

I think it would be difficult to have a system where only python3 is available AND `python` doesnt link to it.

fpp works fine on python3 btw... just the command line -c argument that dont. So just fixing that string decode line could work as well
