### ISSUE TITLE
Command Mode not working in Python3

### ISSUE THREAD

**Issue by edVonSchleck** [facebook/PathPicker#295]
I got an error when tyring to use command mode (Python 3.6):
Line 150 in pathpicker/src/output.py:
bytes object has no attribute encode

Could you fix that?

Thanks.

**Comment by david-caro** [comment]
I seem to be unable to reproduce, tried with python 3.6.3rc1+ on CentOS 7.5 and with python 3.7.1 on Fedora 29.

I'm using the latest master a56e0530e6cbd6bdb9c0eed5789df3952dcb3daa, updated on Nov 21st.

Can you provide a bit more info about the environment you are having the issue in?

**Comment by david-caro** [comment]
Thanks @RicardoMing, I'll look into it, but it looks like it's related to the version of python, can you try updating to a newer one? (>3.6)

**Comment by david-caro** [comment]
Just tried installing anaconda, and setting up python 3.6.5, but was unable to reproduce:

Downloaded and installed the latest anaconda (from https://www.anaconda.com/download/#download), then ran the command:
```
bin/conda create -n 365 python=3.6.5 anaconda
```
Activated the venv:
```
source bin/activate 365
```
And made sure the python is redirected to the same version:
```
$ python --version
Python 3.6.5 :: Anaconda, Inc.
```

But got no error:
```
$ git status | ./fpp
No lines matched!!
```
tried also with something that generated some lines without problems:
```
$ git diff HEAD^^ | ./fpp
nothing to do!
```

@RicardoMing @edVonSchleck can you try running with the PR https://github.com/facebook/PathPicker/pull/296 ? 

That should give us more info. Thanks!

**Comment by RicardoMing** [comment]
This is the new output with Anaconda Python3.6.5.
```
debug_295 $ ls | ./fpp
Traceback (most recent call last):
  File "/home/sjm/GitHub/PathPicker/src/output.py", line 151, in composeFileCommand
    command = command.encode().decode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sjm/GitHub/PathPicker/src/choose.py", line 104, in <module>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/home/sjm/anaconda3/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/sjm/GitHub/PathPicker/src/choose.py", line 104, in <lambda>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/home/sjm/GitHub/PathPicker/src/choose.py", line 46, in doProgram
    screen.control()
  File "/home/sjm/GitHub/PathPicker/src/screenControl.py", line 371, in control
    self.processInput(inKey)
  File "/home/sjm/GitHub/PathPicker/src/screenControl.py", line 446, in processInput
    self.beginEnterCommand()
  File "/home/sjm/GitHub/PathPicker/src/screenControl.py", line 594, in beginEnterCommand
    output.execComposedCommand(command, lineObjs)
  File "/home/sjm/GitHub/PathPicker/src/output.py", line 42, in execComposedCommand
    command = composeCommand(command, lineObjs)
  File "/home/sjm/GitHub/PathPicker/src/output.py", line 146, in composeCommand
    return composeFileCommand(command, lineObjs)
  File "/home/sjm/GitHub/PathPicker/src/output.py", line 153, in composeFileCommand
    raise Exception("Unable to handle command %s" % command)
Exception: Unable to handle command b'vim'
```

**Comment by david-caro** [comment]
Thanks @RicardoMing, It might be an issue with the libraries for curses, what os/curses libraries versions are you using?

In the meantime I'll try to send a PR that handles this in a not-so-nice way :/

**Comment by RicardoMing** [comment]
os: Ubuntu 18.04
```
$ uname -a
Linux neo 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ apt list --installed | grep curses

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libncurses5/bionic-updates,now 6.1-1ubuntu1.18.04 amd64 [installed]
libncurses5-dev/bionic-updates,now 6.1-1ubuntu1.18.04 amd64 [installed]
libncursesw5/bionic-updates,now 6.1-1ubuntu1.18.04 amd64 [installed]
ncurses-base/bionic-updates,bionic-updates,now 6.1-1ubuntu1.18.04 all [installed]
ncurses-bin/bionic-updates,now 6.1-1ubuntu1.18.04 amd64 [installed]
ncurses-term/bionic-updates,bionic-updates,now 6.1-1ubuntu1.18.04 all [installed,automatic]
pinentry-curses/bionic,now 1.1.0-1 amd64 [installed]
```

**Comment by david-caro** [comment]
I thought I had sent the quick fix, sorry, it's been a couple really busy weeks, sent it just now.
