### ISSUE TITLE
-c does not work as expected

### ISSUE THREAD

**Issue by smoya** [facebook/PathPicker#304]
`git branch | fpp -ai -c git checkout` throws an error after selecting a branch.

```bash
Traceback (most recent call last):
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/choose.py", line 100, in <module>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/choose.py", line 100, in <lambda>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/choose.py", line 42, in doProgram
    screen.control()
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/screenControl.py", line 360, in control
    self.processInput(inKey)
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/screenControl.py", line 455, in processInput
    self.onEnter()
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/screenControl.py", line 592, in onEnter
    output.execComposedCommand(presetCommand, lineObjs)
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/output.py", line 42, in execComposedCommand
    command = composeCommand(command, lineObjs)
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/output.py", line 145, in composeCommand
    return composeFileCommand(command, lineObjs)
  File "/usr/local/Cellar/fpp/0.7.2/libexec/src/output.py", line 149, in composeFileCommand
    command = command.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

However, this works:
 `git branch | fpp -ai`, set the command pressing `c` to `git checkout` and then selecting a branch.

**Comment by pcottle** [comment]
I believe this is a python3 vs python2 issue :/ let me see

**Comment by pcottle** [comment]
Actually this was fixed in two different PRs:
https://github.com/facebook/PathPicker/commit/d565a950edd0370c9205735d039e54d7ddbd2060#diff-a535ee5869f641c1108b44e9b8214bf1
https://github.com/facebook/PathPicker/commit/2cea1c522d882f8cc23852bbe25f3ef7b5b05396#diff-a535ee5869f641c1108b44e9b8214bf1

I don't think there's been a version released since then though, so let me try to remember how to do that and send an updated release

**Comment by pcottle** [comment]
Alright new release is up:
https://github.com/Homebrew/homebrew-core/pull/42940

Once that merges, you can upgrade and this will be fixed :) long overdue for a new release!

**Comment by smoya** [comment]
Thanks @pcottle !
Why https://github.com/Homebrew/homebrew-core/pull/42940 was closed?

**Comment by smoya** [comment]
Oh I see, nvm! I upgraded and it works 👏  Thanks again

**Comment by pcottle** [comment]
Woohoo! Yeah the PR got closed so everyone should get the new release. Thanks for the bump to make a new release
