### ISSUE TITLE
choose.py Traceback when running fpp

### ISSUE THREAD

**Issue by jkup** [facebook/PathPicker#45]
Hi all,

I'm assuming this is either something I did or just an environment error but I'm not able to get the tool working on one of my notebooks. Here is what I'm seeing:

```bash
☁  jkup.github.io [master] ⚡ brew install fpp
==> Downloading https://homebrew.bintray.com/bottles/fpp-0.5.5.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/fpp-0.5.5.yosemite.bottle.tar.gz
==> Pouring fpp-0.5.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/fpp/0.5.5: 11 files, 80K
☁  jkup.github.io [master] ⚡ fpp
Using old result...
Traceback (most recent call last):
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/choose.py", line 56, in <module>
    curses.wrapper(doProgram)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/choose.py", line 27, in doProgram
    screen.control()
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 275, in control
    self.printAll()
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 493, in printAll
    self.printChrome()
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 503, in printChrome
    self.helperChrome.output(self.mode)
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 63, in output
    curses.curs_set(INVISIBLE_CURSOR)
_curses.error: curs_set() returned ERR
```

My current version of python is 2.7.9

```bash
☁  jkup.github.io [master] ⚡ python --version
Python 2.7.9
```

I tried it in both zsh and bash but getting the same errors. Not sure if there is any other helpful info I can include. Would love it if you all had any suggestions!

**Comment by jkup** [comment]
Literally 2 minutes after posting this I saw #42. Sorry, closing now!
