### ISSUE TITLE
Curses error

### ISSUE THREAD

**Issue by ashishb** [facebook/PathPicker#60]
https://www.technovelty.org/linux/a-short-tour-of-term.html
My terminal is set to xterm-color and I am getting following error

Traceback (most recent call last):
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/choose.py", line 56, in <module>
    curses.wrapper(doProgram)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/choose.py", line 27, in doProgram
    screen.control()
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 275, in control
    self.printAll()
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 493, in printAll
    self.printChrome()
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 503, in printChrome
    self.helperChrome.output(self.mode)
  File "/usr/local/Cellar/fpp/0.5.5/libexec/src/screenControl.py", line 63, in output
    curses.curs_set(INVISIBLE_CURSOR)
_curses.error: curs_set() returned ERR

**Comment by npike** [comment]
Same.

**Comment by chrisguilbeau** [comment]
+1 same output.

**Comment by frantic** [comment]
Should be fixed by 577936913642847c6a5bfd5bc232baf9b4a2a9e6. @pcottle - can we roll out another minor release? :)

**Comment by pcottle** [comment]
Ah yeah this wasn't pulled into 0.5.5. We added a few other bug fixes and python 3.0 support, so yeah lets add another release!

**Comment by pcottle** [comment]
https://github.com/facebook/PathPicker/releases/tag/0.5.6
https://github.com/Homebrew/homebrew/pull/39616

:tada:

**Comment by pcottle** [comment]
(closing for now, assuming PR is merged. if you guys want you can follow the manual install instructions and get unblocked ASAP since it'll be past frantics fix)
