### ISSUE TITLE
Handle 150 and more lines

### ISSUE THREAD

**Issue by mknecht** [facebook/PathPicker#95]
There seems to be a problem with larger input sets. Is that a known limitation?

```
$ ag html | head -n 150 | fpp
getting input
Traceback (most recent call last):
  File "/home/murat/ws/PathPicker/src/choose.py", line 85, in <module>
    curses.wrapper(doProgram)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/murat/ws/PathPicker/src/choose.py", line 35, in doProgram
    screen.control()
  File "/home/murat/ws/PathPicker/src/screenControl.py", line 281, in control
    self.printAll()
  File "/home/murat/ws/PathPicker/src/screenControl.py", line 497, in printAll
    self.printLines()
  File "/home/murat/ws/PathPicker/src/screenControl.py", line 503, in printLines
    lineObj.output(self.colorPrinter)
  File "/home/murat/ws/PathPicker/src/format.py", line 191, in output
    soFar = self.printUpTo(self.afterText, printer, y, *soFar)
  File "/home/murat/ws/PathPicker/src/format.py", line 175, in printUpTo
    text.printText(y, x, printer, maxPrintable)
  File "/home/murat/ws/PathPicker/src/formattedText.py", line 79, in printText
    printer.screen.addstr(y, x + printedSoFar, toPrint)
_curses.error: addstr() returned ERR
```

Once I reduce the 150 to ~30, it's fine.

**Comment by lastquestion** [comment]
Actually, this is because your console is only about ~30 lines high. 
Fixed in PR #92

**Comment by mknecht** [comment]
Ah, nice! :) Didn't see the connection.

Closing, thanks!

**Comment by pcottle** [comment]
Merged #92, thanks @mknecht for the report!

**Comment by ABDVLGHEYOMSHAMAMDI** [comment]
ABDVLGHEYOMSHAMAMDI

**Comment by ABDVLGHEYOMSHAMAMDI** [comment]
ABDVLGHEYOMSHAMAMDI
عبدالقیوم وطن دوست 
فرزندی عبدالله شامحمدی
ازقریه شولشدره بخشداری
نمکاب اوزه دو 2 
تاریخ 2015_2_24@-}--
34 سیندم
وزنم56کیلو
قدم180. ثانت
